// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgy5pIlUuLXkXmmTQ-XhfF_86nGT83QE',
    appId: '1:551775629027:web:8219d72693fd2729979fd6',
    messagingSenderId: '551775629027',
    projectId: 'notification-b19bb',
    authDomain: 'notification-b19bb.firebaseapp.com',
    storageBucket: 'notification-b19bb.appspot.com',
    measurementId: 'G-45KS2NMH7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUA4DPKP0ICpnPB5OxIAMZ7dJn9k5NCHo',
    appId: '1:551775629027:android:28366a2bcbfbf541979fd6',
    messagingSenderId: '551775629027',
    projectId: 'notification-b19bb',
    storageBucket: 'notification-b19bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp6_tbsrq4cJJKwLTWDUlr_ndWzn78jbU',
    appId: '1:551775629027:ios:23528f3059759f00979fd6',
    messagingSenderId: '551775629027',
    projectId: 'notification-b19bb',
    storageBucket: 'notification-b19bb.appspot.com',
    iosClientId: '551775629027-dcp7fe3m1t46cp7elateff4uknrg10tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notitifcation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp6_tbsrq4cJJKwLTWDUlr_ndWzn78jbU',
    appId: '1:551775629027:ios:40de13453e723901979fd6',
    messagingSenderId: '551775629027',
    projectId: 'notification-b19bb',
    storageBucket: 'notification-b19bb.appspot.com',
    iosClientId: '551775629027-k4vd9p8q8eb6jmerc9calg1fjujckhdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.notitifcation.RunnerTests',
  );
}
